//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRTGAutoTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoTaskCompany
    {
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string AdditionalAddressInformation { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string AlternatePhone1 { get; set; }
        public string AlternatePhone2 { get; set; }
        public string ApiVendorID { get; set; }
        public string AssetValue { get; set; }
        public string BillToCompanyLocationID { get; set; }
        public string BillToAdditionalAddressInformation { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public Nullable<int> BillToAddressToUse { get; set; }
        public string BillToAttention { get; set; }
        public string BillToCity { get; set; }
        public Nullable<int> BillToCountryID { get; set; }
        public string BillToState { get; set; }
        public string BillToZipCode { get; set; }
        public string City { get; set; }
        public Nullable<int> Classification { get; set; }
        public string CompanyName { get; set; }
        public string CompanyNumber { get; set; }
        public Nullable<int> CompanyType { get; set; }
        public string CompetitorID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreatedByResourceID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public string Fax { get; set; }
        public string ImpersonatorCreatorResourceID { get; set; }
        public Nullable<int> InvoiceEmailMessageID { get; set; }
        public Nullable<int> InvoiceMethod { get; set; }
        public string InvoiceNonContractItemsToParentCompany { get; set; }
        public Nullable<int> InvoiceTemplateID { get; set; }
        public string IsActive { get; set; }
        public string IsClientPortalActive { get; set; }
        public string IsEnabledForComanaged { get; set; }
        public string IsTaskFireActive { get; set; }
        public string IsTaxExempt { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public Nullable<System.DateTime> LastTrackedModifiedDateTime { get; set; }
        public string MarketSegmentID { get; set; }
        public Nullable<int> OwnerResourceID { get; set; }
        public Nullable<int> ParentCompanyID { get; set; }
        public string Phone { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> QuoteEmailMessageID { get; set; }
        public Nullable<int> QuoteTemplateID { get; set; }
        public string SicCode { get; set; }
        public string State { get; set; }
        public string StockMarket { get; set; }
        public string StockSymbol { get; set; }
        public string SurveyCompanyRating { get; set; }
        public string TaxID { get; set; }
        public string TaxRegionID { get; set; }
        public string TerritoryID { get; set; }
        public string WebAddress { get; set; }
    }
}
