//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRTGAutoTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoTaskCompanyLocation
    {
        public int Id { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string alternatePhone1 { get; set; }
        public string alternatePhone2 { get; set; }
        public string city { get; set; }
        public Nullable<int> companyID { get; set; }
        public Nullable<int> countryID { get; set; }
        public string description { get; set; }
        public string fax { get; set; }
        public string isActive { get; set; }
        public string isPrimary { get; set; }
        public string isTaxExempt { get; set; }
        public string overrideCompanyTaxSettings { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string postalCode { get; set; }
        public Nullable<double> roundtripDistance { get; set; }
        public string state { get; set; }
        public string taxRegionID { get; set; }
    }
}
