//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRTGAutoTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoTaskConfigurationItem
    {
        public int Id { get; set; }
        public string ApiVendorID { get; set; }
        public Nullable<int> ConfigurationItemCategoryID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string CompanyLocationID { get; set; }
        public Nullable<int> ConfigurationItemType { get; set; }
        public string ContactID { get; set; }
        public string ContractID { get; set; }
        public string ContractServiceBundleID { get; set; }
        public string ContractServiceID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreatedByPersonID { get; set; }
        public string DailyCost { get; set; }
        public string DattoAvailableKilobytes { get; set; }
        public string DattoDeviceMemoryMegabytes { get; set; }
        public string DattoDrivesErrors { get; set; }
        public string DattoHostname { get; set; }
        public string DattoInternalIP { get; set; }
        public string DattoKernelVersionID { get; set; }
        public string DattoLastCheckInDateTime { get; set; }
        public string DattoNICSpeedKilobitsPerSecond { get; set; }
        public string DattoNumberOfAgents { get; set; }
        public string DattoNumberOfDrives { get; set; }
        public string DattoNumberOfVolumes { get; set; }
        public string DattoOffsiteUsedBytes { get; set; }
        public string DattoOSVersionID { get; set; }
        public string DattoPercentageUsed { get; set; }
        public string DattoProtectedKilobytes { get; set; }
        public string DattoRemoteIP { get; set; }
        public string DattoSerialNumber { get; set; }
        public string DattoUptimeSeconds { get; set; }
        public string DattoUsedKilobytes { get; set; }
        public string DattoZFSVersionID { get; set; }
        public string DeviceNetworkingID { get; set; }
        public string HourlyCost { get; set; }
        public string ImpersonatorCreatorResourceID { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public string InstalledByContactID { get; set; }
        public Nullable<int> InstalledByID { get; set; }
        public string IsActive { get; set; }
        public Nullable<int> LastActivityPersonID { get; set; }
        public Nullable<int> LastActivityPersonType { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public string Location { get; set; }
        public string MonthlyCost { get; set; }
        public string Notes { get; set; }
        public string NumberOfUsers { get; set; }
        public string ParentConfigurationItemID { get; set; }
        public string PerUseCost { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ReferenceNumber { get; set; }
        public string ReferenceTitle { get; set; }
        public Nullable<int> RmmDeviceAuditAntivirusStatusID { get; set; }
        public Nullable<int> RmmDeviceAuditArchitectureID { get; set; }
        public string RmmDeviceAuditBackupStatusID { get; set; }
        public string RmmDeviceAuditDescription { get; set; }
        public Nullable<int> RmmDeviceAuditDeviceTypeID { get; set; }
        public Nullable<int> RmmDeviceAuditDisplayAdaptorID { get; set; }
        public Nullable<int> RmmDeviceAuditDomainID { get; set; }
        public string RmmDeviceAuditExternalIPAddress { get; set; }
        public string RmmDeviceAuditHostname { get; set; }
        public string RmmDeviceAuditIPAddress { get; set; }
        public string RmmDeviceAuditMacAddress { get; set; }
        public Nullable<int> RmmDeviceAuditManufacturerID { get; set; }
        public Nullable<int> RmmDeviceAuditMemoryBytes { get; set; }
        public Nullable<int> RmmDeviceAuditMissingPatchCount { get; set; }
        public string RmmDeviceAuditMobileNetworkOperatorID { get; set; }
        public string RmmDeviceAuditMobileNumber { get; set; }
        public Nullable<int> RmmDeviceAuditModelID { get; set; }
        public Nullable<int> RmmDeviceAuditMotherboardID { get; set; }
        public string RmmDeviceAuditOperatingSystem { get; set; }
        public Nullable<int> RmmDeviceAuditPatchStatusID { get; set; }
        public Nullable<int> RmmDeviceAuditProcessorID { get; set; }
        public Nullable<int> RmmDeviceAuditServicePackID { get; set; }
        public string RmmDeviceAuditSNMPContact { get; set; }
        public string RmmDeviceAuditSNMPLocation { get; set; }
        public string RmmDeviceAuditSNMPName { get; set; }
        public Nullable<int> RmmDeviceAuditSoftwareStatusID { get; set; }
        public Nullable<int> RmmDeviceAuditStorageBytes { get; set; }
        public Nullable<int> RmmDeviceID { get; set; }
        public string RmmDeviceUID { get; set; }
        public Nullable<int> RmmOpenAlertCount { get; set; }
        public string SerialNumber { get; set; }
        public string ServiceBundleID { get; set; }
        public string ServiceID { get; set; }
        public string ServiceLevelAgreementID { get; set; }
        public string SetupFee { get; set; }
        public string SourceChargeID { get; set; }
        public string SourceChargeType { get; set; }
        public string VendorID { get; set; }
        public string WarrantyExpirationDate { get; set; }
        public string RmmDeviceAuditLastUser { get; set; }
    }
}
