//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRTGAutoTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAutoTaskDetail
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string ApiIntegrationCode { get; set; }
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
    }
}
