//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRTGAutoTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPRTGDetail
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public string PRTGServerURL { get; set; }
        public string PRTGServerUserName { get; set; }
        public string PRTGServerPassword { get; set; }
    }
}
