//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRTGAutoTaskScheduler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRTGAutotaskEntities : DbContext
    {
        public PRTGAutotaskEntities()
            : base("name=PRTGAutotaskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<CustomerAutoTaskDetail> CustomerAutoTaskDetails { get; set; }
        public virtual DbSet<CustomerPRTGDetail> CustomerPRTGDetails { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<PRTGGroup> PRTGGroups { get; set; }
        public virtual DbSet<PRTGDevice> PRTGDevices { get; set; }
        public virtual DbSet<AutoTaskCompany> AutoTaskCompanies { get; set; }
        public virtual DbSet<GroupCompanyMapping> GroupCompanyMappings { get; set; }
        public virtual DbSet<AutoTaskConfigurationItem> AutoTaskConfigurationItems { get; set; }
        public virtual DbSet<AutoTaskCompanyLocation> AutoTaskCompanyLocations { get; set; }
        public virtual DbSet<DeviceConfigurationItemsMapping> DeviceConfigurationItemsMappings { get; set; }
        public virtual DbSet<GroupCompanyLocationMapping> GroupCompanyLocationMappings { get; set; }
        public virtual DbSet<PRTGAPIHitDetail> PRTGAPIHitDetails { get; set; }
        public virtual DbSet<NotificationAlert> NotificationAlerts { get; set; }
    }
}
