//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRTGAutoTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationAlert
    {
        public int Id { get; set; }
        public string SiteName { get; set; }
        public string Device { get; set; }
        public string PRTGGroup { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
        public string Sensor { get; set; }
        public string LastStatus { get; set; }
        public string Up { get; set; }
        public string Down { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Company { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
