//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRTGAutoTaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRTGDevice
    {
        public int Id { get; set; }
        public string Group { get; set; }
        public string Host { get; set; }
        public string Location { get; set; }
        public string Probe { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public string Name { get; set; }
        public string Active { get; set; }
        public string DisplayType { get; set; }
        public string Dependency { get; set; }
        public Nullable<int> ParentId { get; set; }
    }
}
